name: ci

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run actionlint
        shell: bash
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color
      - name: Run shellcheck
        run: |
          shellcheck ./.aliases.sh
          shellcheck ./macos/macos.sh
          shellcheck -e SC1071 ./vscode/extensions.zsh
          shellcheck -e SC1071 ./.functions.zsh
          shellcheck -e SC1071 ./.zplug.zsh
          shellcheck -e SC1071 ./.zshenv
          shellcheck -e SC1071 ./.zshrc
          shellcheck -e SC1071 ./asdf_install.zsh
          shellcheck -e SC1071 ./brew_install.zsh
          shellcheck -e SC1071 ./install_japanese_man.zsh
          shellcheck -e SC1090 -e SC1091 -e SC2039 -e SC3010 -e SC3020 -e SC3028 -e SC3046 ./install.sh
