name: ci

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run actionlint
        shell: bash
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color
      - name: Run shellcheck
        run: |
          shellcheck -e SC1071 ./.aliases.sh
          shellcheck -e SC1071 ./.zplug.zsh
          shellcheck -e SC1071 ./.zshenv
          shellcheck -e SC1071 ./.zshrc
          shellcheck -e SC1071 ./brew_install.sh
          shellcheck -e SC1071 ./install.sh
