name: install test

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  install-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: install dotfiles
        run: sh -c "$(curl -s https://raw.githubusercontent.com/108EAA0A/dotfiles/master/install.sh)"
# FIXME: 以下のようなパス長エラーでテストがコケる
# https://github.com/108EAA0A/dotfiles/runs/3531436341
#  choco-test:
#    runs-on: windows-latest
#    steps:
#      - name: install chocolatey
#        run: Invoke-Expression (Invoke-WebRequest https://raw.githubusercontent.com/108EAA0A/dotfiles/master/chocolatey.ps1).Content
